// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 第一个EFCore项目;

#nullable disable

namespace 第一个EFCore项目.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("第一个EFCore项目.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("书名");

                    b.Property<double>("price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(0.0)
                        .HasComment("价格");

                    b.HasKey("id");

                    b.ToTable("T_Book", (string)null);
                });

            modelBuilder.Entity("第一个EFCore项目.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键");

                    b.Property<int>("grade")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasComment("年级");

                    b.Property<DateTime>("indate")
                        .HasColumnType("datetime(6)")
                        .HasComment("入学时间");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("姓名");

                    b.HasKey("id");

                    b.ToTable("T_Student", (string)null);
                });

            modelBuilder.Entity("第一个EFCore项目.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("主键");

                    b.Property<DateTime>("indate")
                        .HasColumnType("datetime(6)")
                        .HasComment("入职时间");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("姓名");

                    b.Property<double>("salary")
                        .HasColumnType("double")
                        .HasComment("薪水");

                    b.HasKey("id");

                    b.ToTable("T_Teacher", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
